/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaone.ui;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.EOFException;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import static java.lang.Thread.MIN_PRIORITY;
import java.net.InetAddress;
import java.net.Socket;
import java.security.InvalidAlgorithmParameterException;
import java.security.InvalidKeyException;
import java.security.NoSuchAlgorithmException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.crypto.BadPaddingException;
import javax.crypto.Cipher;
import javax.crypto.IllegalBlockSizeException;
import javax.crypto.NoSuchPaddingException;
import javax.crypto.SecretKey;
import javax.swing.JOptionPane;
import sun.misc.BASE64Decoder;
import sun.misc.BASE64Encoder;

/**
 *
 * @author EvandroFBL
 */
public class ConversaUICliente extends javax.swing.JFrame {

    public String receivedMessage;
    public String encryptedMessage;
    //public ServerSocket serverSocket;
    public Socket clientSocket;
    public ObjectOutputStream out;
    public ObjectInputStream in;
    public String serverName = "";
    public String clientName = "";
    public SecretKey secretkey;
    /**
     * Creates new form ConversaUI
     */
    public ConversaUICliente() {        
        initComponents();
        jTextFieldMensagem.addActionListener(
                new ActionListener() {

                    @Override
                    public void actionPerformed(ActionEvent e) {
                        sendData(e.getActionCommand());
                    }
                });
    }
    
    public ConversaUICliente(String name, SecretKey sctKey) {
        initComponents();
        jLabelNome.setText(name);
        this.serverName = name;
        this.secretkey = sctKey;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelNome = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaConversa = new javax.swing.JTextArea();
        jButtonEnviar = new javax.swing.JButton();
        jButtonAnexar = new javax.swing.JButton();
        jTextFieldMensagem = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabelNome.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelNome.setText("Nome da pessoa");

        jTextAreaConversa.setEditable(false);
        jTextAreaConversa.setColumns(20);
        jTextAreaConversa.setRows(5);
        jScrollPane1.setViewportView(jTextAreaConversa);

        jButtonEnviar.setText("Enviar");
        jButtonEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEnviarActionPerformed(evt);
            }
        });

        jButtonAnexar.setText("Anexar...");

        jMenu1.setText("Nome do programa");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Opções");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jLabelNome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextFieldMensagem, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonEnviar, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
                            .addComponent(jButtonAnexar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelNome, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonEnviar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonAnexar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTextFieldMensagem))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEnviarActionPerformed
        String message = jTextFieldMensagem.getText();
        sendData(message);
        jTextFieldMensagem.setText("");
    }//GEN-LAST:event_jButtonEnviarActionPerformed

    public void executeClient() {
        try {
            clientSocket = new Socket(InetAddress.getByName("127.0.0.1"), 5000);
            out = new ObjectOutputStream(clientSocket.getOutputStream());
            out.flush();
            in = new ObjectInputStream(clientSocket.getInputStream());
            jTextAreaConversa.append("Aguardando...\n");
            out.writeObject(this.clientName + ">> Conexão Criada!");
            out.flush();
            do {
                try {
                    encryptedMessage = (String) in.readObject();
                    receivedMessage = decrypt(encryptedMessage, this.secretkey);
                    jTextAreaConversa.append(receivedMessage);
                    jTextAreaConversa.setCaretPosition(jTextAreaConversa.getText().length());
                } catch (ClassNotFoundException cnfex) {
                    jTextAreaConversa.append("\nRecebido objeto e tipo desconhecido");
                }
            } while (!receivedMessage.equals("gertrudes"));

            jTextAreaConversa.append("\nConexão Perdida");
            out.close();
            in.close();
            clientSocket.close();
        } catch (EOFException eof) {
            jTextAreaConversa.append("\nConexão Perdida");
        } catch (IOException io) {
        }
    }
    
    private void sendData(String s) {
        try {
            this.receivedMessage = s;
            String encrypted;
            encrypted = encrypt("\n" + this.clientName + ">> " + s, this.secretkey);
            JOptionPane.showMessageDialog(null, encrypted, "ERROR", MIN_PRIORITY);
            out.writeObject(encrypted);
            out.flush();
            jTextAreaConversa.append("\n" + this.clientName + ">> " + s);
        }catch(IOException cnfex){
            jTextAreaConversa.append("\nErro enviando objeto.");
        }
    }
    
    private String encrypt(String data, SecretKey secretKey){
	try{		
            Cipher desCipher = Cipher.getInstance("SistemasDistribuidos/CBC/PKCS5Padding"); /* Must specify the mode explicitly as most JCE providers default to ECB mode!! */
            desCipher.init(Cipher.ENCRYPT_MODE,secretKey);

            //Encrypt Data
            byte[] byteDataToEncrypt = data.getBytes();
            byte[] byteCipherText = desCipher.doFinal(byteDataToEncrypt); 
            String strCipherText = new BASE64Encoder().encode(byteCipherText);
            return strCipherText;
        }catch (NoSuchAlgorithmException noSuchAlgo){
            System.out.println(" No Such Algorithm exists " + noSuchAlgo);
        }
            catch (NoSuchPaddingException noSuchPad){
            System.out.println(" No Such Padding exists " + noSuchPad);
        }
            catch (InvalidKeyException invalidKey){
                System.out.println(" Invalid Key " + invalidKey);
            }

            catch (BadPaddingException badPadding){
                System.out.println(" Bad Padding " + badPadding);
            }

            catch (IllegalBlockSizeException illegalBlockSize){
                System.out.println(" Illegal Block Size " + illegalBlockSize);
            }
        return null;
    }

    private String decrypt(String data, SecretKey secretKey){
	try{		
		Cipher desCipher = Cipher.getInstance("DES/CBC/PKCS5Padding"); /* Must specify the mode explicitly as most JCE providers default to ECB mode!! */		
		desCipher.init(Cipher.DECRYPT_MODE,secretKey,desCipher.getParameters());
		//desCipher.init(Cipher.DECRYPT_MODE,secretKey);

		//Decrypt Data
                byte[] byteCipherText = new BASE64Decoder().decodeBuffer(data);
		byte[] byteDecryptedText = desCipher.doFinal(byteCipherText);
		String strDecryptedText = new String(byteDecryptedText);
		return strDecryptedText;
        }catch (NoSuchAlgorithmException noSuchAlgo){
                System.out.println(" No Such Algorithm exists " + noSuchAlgo);
        }
            catch (NoSuchPaddingException noSuchPad){
                System.out.println(" No Such Padding exists " + noSuchPad);
            }

                catch (InvalidKeyException invalidKey){
                    System.out.println(" Invalid Key " + invalidKey);
                }

                catch (BadPaddingException badPadding){
                    System.out.println(" Bad Padding " + badPadding);
                }

                catch (IllegalBlockSizeException illegalBlockSize){
                    System.out.println(" Illegal Block Size " + illegalBlockSize);
                }

                catch (InvalidAlgorithmParameterException invalidParam){
                    System.out.println(" Invalid Parameter " + invalidParam);
                } catch (IOException ex) {
                    Logger.getLogger(ConversaUIServidor.class.getName()).log(Level.SEVERE, null, ex);
                }
        return null;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConversaUICliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConversaUICliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConversaUICliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConversaUICliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        final ConversaUICliente app =new ConversaUICliente();
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                app.setVisible(true);
            }
        });
        app.executeClient();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAnexar;
    private javax.swing.JButton jButtonEnviar;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextArea jTextAreaConversa;
    private javax.swing.JTextField jTextFieldMensagem;
    // End of variables declaration//GEN-END:variables
}
